# Site settings
title: SpyGraph
email: timb@spygraphsystems.com
url: www.spygraphsystems.com
description: "Secure your company's intellectual property, trade secrets and vendor and supply chain networks from aggressive nation-states."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website



# Build settings
markdown: kramdown
permalink: pretty
